# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{compass-aristo-plugin}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["hpoydar"]
  s.date = %q{2009-08-21}
  s.description = %q{A Compass plugin that provides a CSS3 port of the Aristo UI elements}
  s.email = %q{hpoydar@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "Aristo-24.png",
     "README.md",
     "Rakefile",
     "VERSION",
     "examples/.gitignore",
     "lib/aristo.rb",
     "lib/aristo/compass_plugin.rb",
     "lib/aristo/sass_extensions.rb",
     "sass/aristo/_all.sass",
     "sass/aristo/_buttons.sass",
     "sass/aristo/_controls.sass",
     "sass/aristo/_menus.sass",
     "sass/aristo/_scrollbars.sass",
     "sass/aristo/_text.sass",
     "sass/aristo/_windows.sass",
     "templates/.gitignore"
  ]
  s.homepage = %q{http://github.com/hpoydar/compass-aristo-plugin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Compass plugin that provides a CSS3 port of the Aristo UI elements}
  s.test_files = [
    "examples/aristo/config.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<chriseppstein-compass>, [">= 0"])
    else
      s.add_dependency(%q<chriseppstein-compass>, [">= 0"])
    end
  else
    s.add_dependency(%q<chriseppstein-compass>, [">= 0"])
  end
end
