stylesheet 'aristo.sass', :media => "screen, projection"

image 'aristo_blank.gif'
image 'aristo-button-bezel-blue-o.png'
image 'aristo-button-bezel-blue-x.png'
image 'aristo-button-bezel-o.png'
image 'aristo-button-bezel-x.png'
image 'aristo-checkbox-o.png'
image 'aristo-checkbox-x.png'
image 'aristo-radio-o.png'
image 'aristo-radio-x.png'
image 'aristo-scroller-down-arrow-o.png'
image 'aristo-scroller-down-arrow-track.png'
image 'aristo-scroller-down-arrow-x.png'
image 'aristo-scroller-horizontal-knob.png'
image 'aristo-scroller-horizontal-track.png'
image 'aristo-scroller-left-arrow-track.png'
image 'aristo-scroller-left-arrow.png'
image 'aristo-scroller-right-arrow-track.png'
image 'aristo-scroller-right-arrow.png'
image 'aristo-scroller-up-arrow-track.png'
image 'aristo-scroller-up-arrow.png'
image 'aristo-scroller-vertical-knob.png'
image 'aristo-scroller-vertical-track.png'
image 'aristo-select.png'
image 'aristo-slider-horizontal-track.png'
image 'aristo-slider-knob-o.png'
image 'aristo-slider-knob-x.png'